---

- name: restart iptables
  service:
    name: iptables
    state: restarted

- name: restart ip6tables
  service:
    name: ip6tables
    state: restarted

- name: restart httpd
  debug:
    msg: "This is a no-op, since basic role notifies restart httpd"

- name: restart myproxy
  service:
    name: myproxy-server
    state: restarted
